export const SET_USER = "SET_USER";

export const PERSIST_USER = "PERSIST_USER";

export const ADD_EVENT_MODAL_VISIBILITY = "ADD_EVENT_MODAL_VISIBILITY";

export const  PERSIST_ADD_EVENT_MODAL_VISIBILITY = "PERSIST_ADD_EVENT_MODAL_VISIBILITY"