export const CREATE_USER_ACTION = 'CREATE_USER_ACTION';

export const PERSIST_CREATE_USER_ACTION = 'PERSIST_CREATE_USER_ACTION';

export const LOGIN_USER_ACTION = 'LOGIN_USER_ACTION';

export const PERSIST_LOGIN_USER_ACTION = 'PERSIST_LOGIN_USER_ACTION';

export const SIGNOUT_USER_ACTION = 'SIGNOUT_USER_ACTION';

export const PERSIST_SIGNOUT_USER_ACTION = 'PERSIST_SIGNOUT_USER_ACTION';

export const UPDATE_USER_ACTION = 'UPDATE_USER_ACTION';